import type { ChatRoom } from '@/features/chat/types';

export const chatRooms: ChatRoom[] = [
    {
        id: 'nation-platform',
        kind: 'group',
        name: '국밥팟',
        memberCount: 5,
        timeLabel: '지금',
        lastMessage: '@ 김민수: 님 지금 어디??',
        unreadCount: 3,
        messages: [
            { id: 'm1', sender: 'other', text: '오늘 점심 국밥 어때?', time: '오전 9:28' },
            { id: 'm2', sender: 'me', text: '좋아. 12시 반 가능해', time: '오전 9:31' },
            { id: 'm3', sender: 'other', text: '님 지금 어디??', time: '오전 9:41' },
        ],
    },
    {
        id: 'lab-break',
        kind: 'group',
        name: '현우진 연구실 조교방',
        memberCount: 22,
        timeLabel: '어제',
        lastMessage: '알겠습니다!',
        messages: [
            { id: 'm1', sender: 'system', text: '새 약속 후보가 공유됐어요.', time: '어제' },
            { id: 'm2', sender: 'other', text: '자료는 오늘 중으로 올릴게요.', time: '오후 4:12' },
            { id: 'm3', sender: 'me', text: '알겠습니다!', time: '오후 4:16' },
        ],
    },
    {
        id: 'lol-party',
        kind: 'group',
        name: '롤팟',
        memberCount: 6,
        timeLabel: '2일 전',
        lastMessage: '^ㄱ',
        messages: [
            { id: 'm1', sender: 'other', text: '오늘 한 판?', time: '오후 8:10' },
            { id: 'm2', sender: 'me', text: '^ㄱ', time: '오후 8:12' },
        ],
    },
    {
        id: 'class-council',
        kind: 'group',
        name: '22대 공학 10반 학생회',
        memberCount: 5,
        timeLabel: '지금',
        lastMessage: '수고하셨습니다!',
        messages: [
            { id: 'm1', sender: 'other', text: '회의록 확인 부탁드립니다.', time: '오전 8:48' },
            { id: 'm2', sender: 'me', text: '수고하셨습니다!', time: '오전 8:52' },
        ],
    },
    {
        id: 'kim-gayoung',
        kind: 'direct',
        name: '김가영',
        timeLabel: '지금',
        lastMessage: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',
        unreadCount: 2,
        slots: ['cyan', null, 'cyan', null],
        isActive: true,
        activeColor: '#61dddd',
        messages: [
            { id: 'm1', sender: 'other', text: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ', time: '오전 9:40' },
            { id: 'm2', sender: 'me', text: '왜 이렇게 웃겨졌어', time: '오전 9:41' },
            { id: 'm3', sender: 'other', text: '아니 방금 일정 추천 봐봐', time: '오전 9:42' },
        ],
    },
    {
        id: 'kim-nayoung',
        kind: 'direct',
        name: '김나영',
        timeLabel: '2시간 전',
        lastMessage: '좋아좋아',
        slots: ['green', 'green', null, 'green'],
        messages: [
            { id: 'm1', sender: 'me', text: '금요일 저녁 어때?', time: '오전 7:25' },
            { id: 'm2', sender: 'other', text: '좋아좋아', time: '오전 7:27' },
        ],
    },
    {
        id: 'kim-dayoung',
        kind: 'direct',
        name: '김다영',
        timeLabel: '3시간 전',
        lastMessage: '오!!!',
        slots: ['yellow', null, 'yellow', null],
        isActive: true,
        activeColor: '#61dddd',
        messages: [
            { id: 'm1', sender: 'other', text: '오!!!', time: '오전 6:12' },
            { id: 'm2', sender: 'me', text: '그럼 캘린더에 올려둘게', time: '오전 6:15' },
        ],
    },
    {
        id: 'kim-rayoung',
        kind: 'direct',
        name: '김라영',
        timeLabel: '6시간 전',
        lastMessage: '네넹',
        slots: ['green', null, 'green', 'green'],
        messages: [{ id: 'm1', sender: 'other', text: '네넹', time: '오전 3:41' }],
    },
    {
        id: 'kim-mayoung',
        kind: 'direct',
        name: '김마영',
        timeLabel: '1일 전',
        lastMessage: '그때 봐~~',
        slots: ['cyan', 'yellow', null, 'cyan'],
        isActive: true,
        activeColor: '#61dddd',
        messages: [{ id: 'm1', sender: 'me', text: '그때 봐~~', time: '어제' }],
    },
    {
        id: 'kim-bayoung',
        kind: 'direct',
        name: '김바영',
        timeLabel: '1일 전',
        lastMessage: '오키오키',
        slots: ['green', 'green', null, null],
        messages: [{ id: 'm1', sender: 'other', text: '오키오키', time: '어제' }],
    },
    {
        id: 'songdo-bapyak',
        kind: 'appointment',
        name: '송도 밥약',
        memberCount: 6,
        timeLabel: '3일 전',
        lastMessage: '그때 봅시다~',
        unreadCount: 1,
        messages: [
            { id: 'm1', sender: 'system', text: '약속 시간이 확정됐어요. 7월 2일 오후 6:30', time: '3일 전' },
            { id: 'm2', sender: 'other', text: '그때 봅시다~', time: '3일 전' },
        ],
    },
];
